openapi: 3.0.0
info:
  version: 1.0.0
  title: PXN OpenAPI
  contact:
    email: yuchanghong@pxn.one
servers:
  - url: 'https://api.{BROKER_DOMAIN}/api/v1'
tags:
  - name: Withdrawal
    description: User Withdrawals
  - name: Deposit
    description: User Deposits
paths:
  /customers:
    post:
      tags:
        - Customer
      summary: Create customer
      description: 'Create customer. Required **customer:write** scope.'
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/CreateCustomerBody'
      responses:
        '201':
          description: create customer success
      security:
        - bearerAuth:
          - wallet:write
  /deposits:
    get:
      tags:
        - Deposit
      summary: Get User Deposit History
      description: 'Returns user deposits. Required **wallet:read** scope.'
      operationId: getDeposits
      parameters:
        - in: query
          name: asset_symbol
          description: Asset Symbol
          required: true
          schema:
            type: string
            example: EOS
        - in: query
          name: limit
          description: 'Returns limited size of records '
          required: false
          schema:
            type: integer
        - in: query
          name: offset_id
          description: Returns records after this ID
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of deposits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deposit'
      security:
        - bearerAuth:
          - wallet:read
  /withdrawals:
    get:
      tags:
        - Withdrawal
      summary: Get User Withdrawal History
      description: 'Returns user withdrawals. Required **wallet:read** scope.'
      operationId: getWithdrawal
      parameters:
        - in: query
          name: asset
          description: Asset Name
          required: true
          schema:
            type: string
        - in: query
          name: limit
          description: 'Returns limited size of records '
          required: false
          schema:
            type: integer
        - in: query
          name: offset_id
          description: Returns records after this ID
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of withdrawal
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Withdrawal'
      security:
        - bearerAuth:
          - wallet:read
    post:
      tags:
        - Withdrawal
      summary: Create Withdrawal
      description: 'Create user withdrawal. Required **wallet:write** scope.'
      operationId: createWithdrawal
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/CreateWithdrawalBody'
      responses:
        '200':
          description: create withdrawal success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Withdrawal'
      security:
        - bearerAuth:
          - wallet:write
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    CreateCustomerBody:
      type: object
      properties:
        email:
          type: string
          description: User Email
          required: true
          example: test@pxn.one
        mobile:
          type: string
          description: User Mobile
          example: 13888888888
        nation_code:
          type: string
          description: User Mobile
          example: 86
        identity:
          type: string
          description: User identity
          required: true
          example: SOME_IDENTITY
    CreateWithdrawalBody:
      type: object
      properties:
        asset_symbol:
          type: string
          description: Asset Symbol
          required: true
          example: EOS
        amount:
          type: string
          description: Withdraw Amount
          required: true
        type:
          type: string
          description: Withdraw type
          required: true
          enum:
            - INTERNAL
            - NORMAL
        identity:
          type: string
          description: Withdraw identity. Only avalible when withdraw type is `INTERNAL`.
          format: int64
        address:
          type: string
          description: Withdraw Address. Only avalible when withdraw type is `NORMAL`.
          format: int64
  schemas:
    Withdrawal:
      type: object
      properties:
        id:
          type: integer
          description: Withdraw ID
          format: int64
        state:
          type: string
          description: Withdraw Status
          enum:
            - PENDING
            - TRANSACTION_CREATED
            - COMPLETED
            - FAILED
        identity:
          type: string
          description: Internal withdraw Recipient Identity
          example: SOME_IDENTITY
        asset_symbol:
          type: string
          description: Asset Symbol
          example: EOS
        amount:
          type: string
          description: Withdraw Amount
          example: '200.124'
        address:
          type: string
          description: Withdraw Address
          example: '0x3c35858196C43e9Db361445dAc49Df61a177629b'
        completed_at:
          type: string
          description: Withdraw completed at
          format: date-time
        created_at:
          type: string
          description: Withdraw record created at
          format: date-time
        type:
          type: string
          description: Withdraw Type
          enum:
            - ON_CHAIN
            - OFF_CHAIN
            - INTERNAL
    Deposit:
      type: object
      properties:
        id:
          type: integer
          description: Deposit ID
          format: int64
        state:
          type: string
          description: Deposit Status
          enum:
            - PENDING
            - CONFIRMED
        asset_symbol:
          type: string
          description: Asset Symbol
          example: EOS
        identity:
          type: string
          description: Internal deposit identity. If this field is not null, this is a internal deposit
          example: some_identity
        confirms:
          type: integer
          description: Deposit comfirms
          format: int64
          example: 2
        txid:
          type: string
          description: Deposit transaction ID
        amount:
          type: string
          description: Withdraw Amount
          example: '200.124'
        note:
          type: string
          description: Deposit note
        confirmed_at:
          type: string
          description: Deposit confirmated at
          format: date-time
        created_at:
          type: string
          description: Deposit record created at
          format: date-time
